---
services:
    frontend:
        container_name: hypentor-frontend
        pull_policy: build
        build:
            context: ..
            dockerfile: docker/frontend.dockerfile
            target: frontend-prod
        image: hypentor-frontend
        ports:
            - 3000:3000
        environment:
            - BACKEND_ORIGIN=http://backend:8080

networks:
    app-network:
        driver: bridge
